server.port=8080
server.error.whitelabel.enabled=false
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
spring.application.name=nxt-sts
info.app.version=@project.version@
springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/v3/api-docs
